'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  IBOReportOfflineDetail.vb
''  Implementation of the Interface IBOReportOfflineDetail
''  Generated by Enterprise Architect
''  Created on:      30-Sep-2004 12:20:34
''  Original author: Paul Wade
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Interface IBOReportDetail


    Property PaymentDateTime() As DateTime

    Property Notes() As String

End Interface ' IBOReportOfflineDetail
