'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class SemiCompleteReminderLetterData
    Inherits DataSet
    
    Private tableBOSemiCompleteReminderLetter As BOSemiCompleteReminderLetterDataTable
    
    Private tableBOSemiCompleteReminderLetterDetails As BOSemiCompleteReminderLetterDetailsDataTable
    
    Private relationBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails As DataRelation
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("BOSemiCompleteReminderLetter")) Is Nothing) Then
                Me.Tables.Add(New BOSemiCompleteReminderLetterDataTable(ds.Tables("BOSemiCompleteReminderLetter")))
            End If
            If (Not (ds.Tables("BOSemiCompleteReminderLetterDetails")) Is Nothing) Then
                Me.Tables.Add(New BOSemiCompleteReminderLetterDetailsDataTable(ds.Tables("BOSemiCompleteReminderLetterDetails")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BOSemiCompleteReminderLetter As BOSemiCompleteReminderLetterDataTable
        Get
            Return Me.tableBOSemiCompleteReminderLetter
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BOSemiCompleteReminderLetterDetails As BOSemiCompleteReminderLetterDetailsDataTable
        Get
            Return Me.tableBOSemiCompleteReminderLetterDetails
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As SemiCompleteReminderLetterData = CType(MyBase.Clone,SemiCompleteReminderLetterData)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("BOSemiCompleteReminderLetter")) Is Nothing) Then
            Me.Tables.Add(New BOSemiCompleteReminderLetterDataTable(ds.Tables("BOSemiCompleteReminderLetter")))
        End If
        If (Not (ds.Tables("BOSemiCompleteReminderLetterDetails")) Is Nothing) Then
            Me.Tables.Add(New BOSemiCompleteReminderLetterDetailsDataTable(ds.Tables("BOSemiCompleteReminderLetterDetails")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableBOSemiCompleteReminderLetter = CType(Me.Tables("BOSemiCompleteReminderLetter"),BOSemiCompleteReminderLetterDataTable)
        If (Not (Me.tableBOSemiCompleteReminderLetter) Is Nothing) Then
            Me.tableBOSemiCompleteReminderLetter.InitVars
        End If
        Me.tableBOSemiCompleteReminderLetterDetails = CType(Me.Tables("BOSemiCompleteReminderLetterDetails"),BOSemiCompleteReminderLetterDetailsDataTable)
        If (Not (Me.tableBOSemiCompleteReminderLetterDetails) Is Nothing) Then
            Me.tableBOSemiCompleteReminderLetterDetails.InitVars
        End If
        Me.relationBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails = Me.Relations("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails")
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "SemiCompleteReminderLetterData"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/SemiCompleteReminderLetterData.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableBOSemiCompleteReminderLetter = New BOSemiCompleteReminderLetterDataTable
        Me.Tables.Add(Me.tableBOSemiCompleteReminderLetter)
        Me.tableBOSemiCompleteReminderLetterDetails = New BOSemiCompleteReminderLetterDetailsDataTable
        Me.Tables.Add(Me.tableBOSemiCompleteReminderLetterDetails)
        Dim fkc As ForeignKeyConstraint
        fkc = New ForeignKeyConstraint("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails", New DataColumn() {Me.tableBOSemiCompleteReminderLetter.IdColumn}, New DataColumn() {Me.tableBOSemiCompleteReminderLetterDetails.IdColumn})
        Me.tableBOSemiCompleteReminderLetterDetails.Constraints.Add(fkc)
        fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None
        fkc.DeleteRule = System.Data.Rule.Cascade
        fkc.UpdateRule = System.Data.Rule.Cascade
        Me.relationBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails = New DataRelation("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails", New DataColumn() {Me.tableBOSemiCompleteReminderLetter.IdColumn}, New DataColumn() {Me.tableBOSemiCompleteReminderLetterDetails.IdColumn}, false)
        Me.Relations.Add(Me.relationBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails)
    End Sub
    
    Private Function ShouldSerializeBOSemiCompleteReminderLetter() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializeBOSemiCompleteReminderLetterDetails() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub BOSemiCompleteReminderLetterRowChangeEventHandler(ByVal sender As Object, ByVal e As BOSemiCompleteReminderLetterRowChangeEvent)
    
    Public Delegate Sub BOSemiCompleteReminderLetterDetailsRowChangeEventHandler(ByVal sender As Object, ByVal e As BOSemiCompleteReminderLetterDetailsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnId As DataColumn
        
        Private columnFromAddress As DataColumn
        
        Private columnToAddress As DataColumn
        
        Private columnIssuedDate As DataColumn
        
        Private columnSalutation As DataColumn
        
        Private columnBeginText As DataColumn
        
        Private columnIntroText As DataColumn
        
        Private columnValidYearText As DataColumn
        
        Private columnEndText As DataColumn
        
        Private columnDirectLineText As DataColumn
        
        Private columnSignatureText As DataColumn
        
        Private columnFaxText As DataColumn
        
        Private columnEMailText As DataColumn
        
        Friend Sub New()
            MyBase.New("BOSemiCompleteReminderLetter")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property IdColumn As DataColumn
            Get
                Return Me.columnId
            End Get
        End Property
        
        Friend ReadOnly Property FromAddressColumn As DataColumn
            Get
                Return Me.columnFromAddress
            End Get
        End Property
        
        Friend ReadOnly Property ToAddressColumn As DataColumn
            Get
                Return Me.columnToAddress
            End Get
        End Property
        
        Friend ReadOnly Property IssuedDateColumn As DataColumn
            Get
                Return Me.columnIssuedDate
            End Get
        End Property
        
        Friend ReadOnly Property SalutationColumn As DataColumn
            Get
                Return Me.columnSalutation
            End Get
        End Property
        
        Friend ReadOnly Property BeginTextColumn As DataColumn
            Get
                Return Me.columnBeginText
            End Get
        End Property
        
        Friend ReadOnly Property IntroTextColumn As DataColumn
            Get
                Return Me.columnIntroText
            End Get
        End Property
        
        Friend ReadOnly Property ValidYearTextColumn As DataColumn
            Get
                Return Me.columnValidYearText
            End Get
        End Property
        
        Friend ReadOnly Property EndTextColumn As DataColumn
            Get
                Return Me.columnEndText
            End Get
        End Property
        
        Friend ReadOnly Property DirectLineTextColumn As DataColumn
            Get
                Return Me.columnDirectLineText
            End Get
        End Property
        
        Friend ReadOnly Property SignatureTextColumn As DataColumn
            Get
                Return Me.columnSignatureText
            End Get
        End Property
        
        Friend ReadOnly Property FaxTextColumn As DataColumn
            Get
                Return Me.columnFaxText
            End Get
        End Property
        
        Friend ReadOnly Property EMailTextColumn As DataColumn
            Get
                Return Me.columnEMailText
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As BOSemiCompleteReminderLetterRow
            Get
                Return CType(Me.Rows(index),BOSemiCompleteReminderLetterRow)
            End Get
        End Property
        
        Public Event BOSemiCompleteReminderLetterRowChanged As BOSemiCompleteReminderLetterRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterRowChanging As BOSemiCompleteReminderLetterRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterRowDeleted As BOSemiCompleteReminderLetterRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterRowDeleting As BOSemiCompleteReminderLetterRowChangeEventHandler
        
        Public Overloads Sub AddBOSemiCompleteReminderLetterRow(ByVal row As BOSemiCompleteReminderLetterRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddBOSemiCompleteReminderLetterRow(ByVal Id As Long, ByVal FromAddress As String, ByVal ToAddress As String, ByVal IssuedDate As String, ByVal Salutation As String, ByVal BeginText As String, ByVal IntroText As String, ByVal ValidYearText As String, ByVal EndText As String, ByVal DirectLineText As String, ByVal SignatureText As String, ByVal FaxText As String, ByVal EMailText As String) As BOSemiCompleteReminderLetterRow
            Dim rowBOSemiCompleteReminderLetterRow As BOSemiCompleteReminderLetterRow = CType(Me.NewRow,BOSemiCompleteReminderLetterRow)
            rowBOSemiCompleteReminderLetterRow.ItemArray = New Object() {Id, FromAddress, ToAddress, IssuedDate, Salutation, BeginText, IntroText, ValidYearText, EndText, DirectLineText, SignatureText, FaxText, EMailText}
            Me.Rows.Add(rowBOSemiCompleteReminderLetterRow)
            Return rowBOSemiCompleteReminderLetterRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As BOSemiCompleteReminderLetterDataTable = CType(MyBase.Clone,BOSemiCompleteReminderLetterDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New BOSemiCompleteReminderLetterDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnId = Me.Columns("Id")
            Me.columnFromAddress = Me.Columns("FromAddress")
            Me.columnToAddress = Me.Columns("ToAddress")
            Me.columnIssuedDate = Me.Columns("IssuedDate")
            Me.columnSalutation = Me.Columns("Salutation")
            Me.columnBeginText = Me.Columns("BeginText")
            Me.columnIntroText = Me.Columns("IntroText")
            Me.columnValidYearText = Me.Columns("ValidYearText")
            Me.columnEndText = Me.Columns("EndText")
            Me.columnDirectLineText = Me.Columns("DirectLineText")
            Me.columnSignatureText = Me.Columns("SignatureText")
            Me.columnFaxText = Me.Columns("FaxText")
            Me.columnEMailText = Me.Columns("EMailText")
        End Sub
        
        Private Sub InitClass()
            Me.columnId = New DataColumn("Id", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnId)
            Me.columnFromAddress = New DataColumn("FromAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFromAddress)
            Me.columnToAddress = New DataColumn("ToAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnToAddress)
            Me.columnIssuedDate = New DataColumn("IssuedDate", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIssuedDate)
            Me.columnSalutation = New DataColumn("Salutation", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSalutation)
            Me.columnBeginText = New DataColumn("BeginText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnBeginText)
            Me.columnIntroText = New DataColumn("IntroText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIntroText)
            Me.columnValidYearText = New DataColumn("ValidYearText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnValidYearText)
            Me.columnEndText = New DataColumn("EndText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnEndText)
            Me.columnDirectLineText = New DataColumn("DirectLineText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDirectLineText)
            Me.columnSignatureText = New DataColumn("SignatureText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSignatureText)
            Me.columnFaxText = New DataColumn("FaxText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFaxText)
            Me.columnEMailText = New DataColumn("EMailText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnEMailText)
            Me.Constraints.Add(New UniqueConstraint("key1", New DataColumn() {Me.columnId}, false))
            Me.columnId.AllowDBNull = false
            Me.columnId.Unique = true
        End Sub
        
        Public Function NewBOSemiCompleteReminderLetterRow() As BOSemiCompleteReminderLetterRow
            Return CType(Me.NewRow,BOSemiCompleteReminderLetterRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New BOSemiCompleteReminderLetterRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(BOSemiCompleteReminderLetterRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BOSemiCompleteReminderLetterRowChangedEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterRowChanged(Me, New BOSemiCompleteReminderLetterRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BOSemiCompleteReminderLetterRowChangingEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterRowChanging(Me, New BOSemiCompleteReminderLetterRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BOSemiCompleteReminderLetterRowDeletedEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterRowDeleted(Me, New BOSemiCompleteReminderLetterRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BOSemiCompleteReminderLetterRowDeletingEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterRowDeleting(Me, New BOSemiCompleteReminderLetterRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveBOSemiCompleteReminderLetterRow(ByVal row As BOSemiCompleteReminderLetterRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterRow
        Inherits DataRow
        
        Private tableBOSemiCompleteReminderLetter As BOSemiCompleteReminderLetterDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableBOSemiCompleteReminderLetter = CType(Me.Table,BOSemiCompleteReminderLetterDataTable)
        End Sub
        
        Public Property Id As Long
            Get
                Return CType(Me(Me.tableBOSemiCompleteReminderLetter.IdColumn),Long)
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.IdColumn) = value
            End Set
        End Property
        
        Public Property FromAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.FromAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.FromAddressColumn) = value
            End Set
        End Property
        
        Public Property ToAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.ToAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.ToAddressColumn) = value
            End Set
        End Property
        
        Public Property IssuedDate As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.IssuedDateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.IssuedDateColumn) = value
            End Set
        End Property
        
        Public Property Salutation As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.SalutationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.SalutationColumn) = value
            End Set
        End Property
        
        Public Property BeginText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.BeginTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.BeginTextColumn) = value
            End Set
        End Property
        
        Public Property IntroText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.IntroTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.IntroTextColumn) = value
            End Set
        End Property
        
        Public Property ValidYearText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.ValidYearTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.ValidYearTextColumn) = value
            End Set
        End Property
        
        Public Property EndText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.EndTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.EndTextColumn) = value
            End Set
        End Property
        
        Public Property DirectLineText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.DirectLineTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.DirectLineTextColumn) = value
            End Set
        End Property
        
        Public Property SignatureText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.SignatureTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.SignatureTextColumn) = value
            End Set
        End Property
        
        Public Property FaxText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.FaxTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.FaxTextColumn) = value
            End Set
        End Property
        
        Public Property EMailText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetter.EMailTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetter.EMailTextColumn) = value
            End Set
        End Property
        
        Public Function IsFromAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.FromAddressColumn)
        End Function
        
        Public Sub SetFromAddressNull()
            Me(Me.tableBOSemiCompleteReminderLetter.FromAddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsToAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.ToAddressColumn)
        End Function
        
        Public Sub SetToAddressNull()
            Me(Me.tableBOSemiCompleteReminderLetter.ToAddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIssuedDateNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.IssuedDateColumn)
        End Function
        
        Public Sub SetIssuedDateNull()
            Me(Me.tableBOSemiCompleteReminderLetter.IssuedDateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSalutationNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.SalutationColumn)
        End Function
        
        Public Sub SetSalutationNull()
            Me(Me.tableBOSemiCompleteReminderLetter.SalutationColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsBeginTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.BeginTextColumn)
        End Function
        
        Public Sub SetBeginTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.BeginTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIntroTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.IntroTextColumn)
        End Function
        
        Public Sub SetIntroTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.IntroTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsValidYearTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.ValidYearTextColumn)
        End Function
        
        Public Sub SetValidYearTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.ValidYearTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsEndTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.EndTextColumn)
        End Function
        
        Public Sub SetEndTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.EndTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDirectLineTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.DirectLineTextColumn)
        End Function
        
        Public Sub SetDirectLineTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.DirectLineTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSignatureTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.SignatureTextColumn)
        End Function
        
        Public Sub SetSignatureTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.SignatureTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsFaxTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.FaxTextColumn)
        End Function
        
        Public Sub SetFaxTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.FaxTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsEMailTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetter.EMailTextColumn)
        End Function
        
        Public Sub SetEMailTextNull()
            Me(Me.tableBOSemiCompleteReminderLetter.EMailTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function GetBOSemiCompleteReminderLetterDetailsRows() As BOSemiCompleteReminderLetterDetailsRow()
            Return CType(Me.GetChildRows(Me.Table.ChildRelations("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails")),BOSemiCompleteReminderLetterDetailsRow())
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As BOSemiCompleteReminderLetterRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As BOSemiCompleteReminderLetterRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As BOSemiCompleteReminderLetterRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterDetailsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnId As DataColumn
        
        Private columnPermitNoText As DataColumn
        
        Friend Sub New()
            MyBase.New("BOSemiCompleteReminderLetterDetails")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property IdColumn As DataColumn
            Get
                Return Me.columnId
            End Get
        End Property
        
        Friend ReadOnly Property PermitNoTextColumn As DataColumn
            Get
                Return Me.columnPermitNoText
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As BOSemiCompleteReminderLetterDetailsRow
            Get
                Return CType(Me.Rows(index),BOSemiCompleteReminderLetterDetailsRow)
            End Get
        End Property
        
        Public Event BOSemiCompleteReminderLetterDetailsRowChanged As BOSemiCompleteReminderLetterDetailsRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterDetailsRowChanging As BOSemiCompleteReminderLetterDetailsRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterDetailsRowDeleted As BOSemiCompleteReminderLetterDetailsRowChangeEventHandler
        
        Public Event BOSemiCompleteReminderLetterDetailsRowDeleting As BOSemiCompleteReminderLetterDetailsRowChangeEventHandler
        
        Public Overloads Sub AddBOSemiCompleteReminderLetterDetailsRow(ByVal row As BOSemiCompleteReminderLetterDetailsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddBOSemiCompleteReminderLetterDetailsRow(ByVal parentBOSemiCompleteReminderLetterRowByBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails As BOSemiCompleteReminderLetterRow, ByVal PermitNoText As String) As BOSemiCompleteReminderLetterDetailsRow
            Dim rowBOSemiCompleteReminderLetterDetailsRow As BOSemiCompleteReminderLetterDetailsRow = CType(Me.NewRow,BOSemiCompleteReminderLetterDetailsRow)
            rowBOSemiCompleteReminderLetterDetailsRow.ItemArray = New Object() {parentBOSemiCompleteReminderLetterRowByBOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails(0), PermitNoText}
            Me.Rows.Add(rowBOSemiCompleteReminderLetterDetailsRow)
            Return rowBOSemiCompleteReminderLetterDetailsRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As BOSemiCompleteReminderLetterDetailsDataTable = CType(MyBase.Clone,BOSemiCompleteReminderLetterDetailsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New BOSemiCompleteReminderLetterDetailsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnId = Me.Columns("Id")
            Me.columnPermitNoText = Me.Columns("PermitNoText")
        End Sub
        
        Private Sub InitClass()
            Me.columnId = New DataColumn("Id", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnId)
            Me.columnPermitNoText = New DataColumn("PermitNoText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPermitNoText)
        End Sub
        
        Public Function NewBOSemiCompleteReminderLetterDetailsRow() As BOSemiCompleteReminderLetterDetailsRow
            Return CType(Me.NewRow,BOSemiCompleteReminderLetterDetailsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New BOSemiCompleteReminderLetterDetailsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(BOSemiCompleteReminderLetterDetailsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BOSemiCompleteReminderLetterDetailsRowChangedEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterDetailsRowChanged(Me, New BOSemiCompleteReminderLetterDetailsRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterDetailsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BOSemiCompleteReminderLetterDetailsRowChangingEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterDetailsRowChanging(Me, New BOSemiCompleteReminderLetterDetailsRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterDetailsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BOSemiCompleteReminderLetterDetailsRowDeletedEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterDetailsRowDeleted(Me, New BOSemiCompleteReminderLetterDetailsRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterDetailsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BOSemiCompleteReminderLetterDetailsRowDeletingEvent) Is Nothing) Then
                RaiseEvent BOSemiCompleteReminderLetterDetailsRowDeleting(Me, New BOSemiCompleteReminderLetterDetailsRowChangeEvent(CType(e.Row,BOSemiCompleteReminderLetterDetailsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveBOSemiCompleteReminderLetterDetailsRow(ByVal row As BOSemiCompleteReminderLetterDetailsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterDetailsRow
        Inherits DataRow
        
        Private tableBOSemiCompleteReminderLetterDetails As BOSemiCompleteReminderLetterDetailsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableBOSemiCompleteReminderLetterDetails = CType(Me.Table,BOSemiCompleteReminderLetterDetailsDataTable)
        End Sub
        
        Public Property Id As Long
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetterDetails.IdColumn),Long)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetterDetails.IdColumn) = value
            End Set
        End Property
        
        Public Property PermitNoText As String
            Get
                Try 
                    Return CType(Me(Me.tableBOSemiCompleteReminderLetterDetails.PermitNoTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOSemiCompleteReminderLetterDetails.PermitNoTextColumn) = value
            End Set
        End Property
        
        Public Property BOSemiCompleteReminderLetterRow As BOSemiCompleteReminderLetterRow
            Get
                Return CType(Me.GetParentRow(Me.Table.ParentRelations("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails")),BOSemiCompleteReminderLetterRow)
            End Get
            Set
                Me.SetParentRow(value, Me.Table.ParentRelations("BOSemiCompleteReminderLetterBOSemiCompleteReminderLetterDetails"))
            End Set
        End Property
        
        Public Function IsIdNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetterDetails.IdColumn)
        End Function
        
        Public Sub SetIdNull()
            Me(Me.tableBOSemiCompleteReminderLetterDetails.IdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPermitNoTextNull() As Boolean
            Return Me.IsNull(Me.tableBOSemiCompleteReminderLetterDetails.PermitNoTextColumn)
        End Function
        
        Public Sub SetPermitNoTextNull()
            Me(Me.tableBOSemiCompleteReminderLetterDetails.PermitNoTextColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOSemiCompleteReminderLetterDetailsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As BOSemiCompleteReminderLetterDetailsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As BOSemiCompleteReminderLetterDetailsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As BOSemiCompleteReminderLetterDetailsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
