<%@ Page Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="Route.aspx.cs"
    Inherits="Discovery.UI.Web.ReferenceData.Route" Title="Management Server - Routes" %>

<%@ Import Namespace="System.Web.UI.WebControls" %>
<%@ Import Namespace="System.Web.UI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="Server">
    <!-- Script Manager Proxy -->
    <asp:ScriptManagerProxy ID="scriptManagerProxy" runat="server" />
    <asp:Label ID="LabelPageTitle" runat="server" CssClass="PageTitle" Text="Routes"></asp:Label><br />
    <hr />
    <asp:HyperLink ID="HyperLinkBack"  SkinID="HyperLinkBack" runat="server">Back</asp:HyperLink><br />
    <asp:UpdatePanel ID="RouteUpdatePanel" runat="server" UpdateMode="Always">
    <ContentTemplate>
<asp:FormView id="RouteFormView" runat="server" DataSourceID="RouteDataSource" EnableViewState="False" DataKeyNames="Id,Code"><EditItemTemplate>
<asp:ImageButton id="ButtonUpdate" onclick="ButtonUpdate_Click" runat="server" SkinID="ButtonSave" CommandName="Update" CausesValidation="True"></asp:ImageButton><asp:ImageButton id="ButtonUpdateCancel" runat="server" SkinID="ButtonCancel" CommandName="Cancel" CausesValidation="False"></asp:ImageButton><BR /><DIV><TABLE style="WIDTH: 426px" id="Table3"><TBODY><TR><TD style="WIDTH: 98px">Code:</TD><TD style="WIDTH: 128px"><asp:TextBox id="TextBoxCode" runat="server" Text='<%# Bind("Code") %>'></asp:TextBox></TD></TR><TR><TD style="WIDTH: 98px; HEIGHT: 21px">Description:</TD><TD style="WIDTH: 128px; HEIGHT: 21px"><asp:TextBox id="TextBoxDescription" runat="server" Text='<%# Bind("Description") %>'></asp:TextBox></TD></TR><TR><TD style="WIDTH: 98px; HEIGHT: 19px">Warehouse Code:</TD><TD style="WIDTH: 128px; HEIGHT: 19px"><asp:DropDownList id="DropDownListWarehouseCode" runat="server" DataSourceID="ObjectDataSourceWarehouse" DataValueField="Id" DataTextField="Code" SelectedValue='<%# Bind("WarehouseId") %>'></asp:DropDownList><asp:ObjectDataSource id="ObjectDataSourceWarehouse" runat="server" TypeName="Discovery.BusinessObjects.Controllers.WarehouseController" SelectMethod="GetWarehouses">
                            </asp:ObjectDataSource> </TD></TR><TR><TD style="WIDTH: 98px">Is Same Day?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsSameDay" runat="server" OnCheckedChanged="CheckBoxIsSameDay_CheckedChanged" Checked='<%# Bind("IsSameDay") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 98px">Is Next Day?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsNextDay" runat="server" OnCheckedChanged="CheckBoxIsNextDay_CheckedChanged" Checked='<%# Bind("IsNextDay") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 98px">Is Collection?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsCollection" runat="server" OnCheckedChanged="CheckBoxIsCollection_CheckedChanged" Checked='<%# Bind("IsCollection") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 98px">Is Special?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsSpecial" runat="server" OnCheckedChanged="CheckBoxIsSpecial_CheckedChanged" Checked='<%# Bind("IsSpecial") %>'></asp:CheckBox></TD></TR></TBODY></TABLE><asp:HiddenField id="Id" runat="server" Value='<%# Bind("Id") %>'></asp:HiddenField> <asp:HiddenField id="CheckSum" runat="server" Value='<%# Bind("CheckSum") %>'></asp:HiddenField> <asp:HiddenField id="IsArchived" runat="server" Value='<%# Bind("IsArchived") %>'></asp:HiddenField> <asp:HiddenField id="UpdatedBy" runat="server" Value='<%# Bind("UpdatedBy") %>'></asp:HiddenField> <!-- AJAX EXTENDERS --><ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender1" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsSameDay" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender2" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsNextDay" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender3" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsCollection" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender4" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsSpecial" Enabled="false"></ajaxToolkit:ToggleButtonExtender> </DIV>
</EditItemTemplate>
<InsertItemTemplate>
<asp:ImageButton id="InsertButton" onclick="InsertButton_Click" runat="server" SkinID="ButtonInsert" CommandName="Insert" CausesValidation="True"></asp:ImageButton><asp:ImageButton id="InsertCancelButton" onclick="InsertCancelButton_Click" runat="server" SkinID="ButtonCancel" CommandName="Cancel" CausesValidation="False"></asp:ImageButton><BR /><DIV><TABLE style="WIDTH: 426px" id="Table2"><TBODY><TR><TD style="WIDTH: 69px">Code:</TD><TD style="WIDTH: 128px"><asp:TextBox id="TextBoxCode" runat="server" Text='<%# Bind("Code") %>'></asp:TextBox></TD></TR><TR><TD style="WIDTH: 69px">Description:</TD><TD style="WIDTH: 128px"><asp:TextBox id="TextBoxDescription" runat="server" Text='<%# Bind("Description") %>'></asp:TextBox></TD></TR><TR><TD style="WIDTH: 69px">Warehouse Code:</TD><TD style="WIDTH: 128px"><asp:DropDownList id="DropDownList1" runat="server" DataSourceID="ObjectDataSourceWarehouse" DataValueField="Id" DataTextField="Code" SelectedValue='<%# Bind("WarehouseId") %>'></asp:DropDownList><asp:ObjectDataSource id="ObjectDataSourceWarehouse" runat="server" TypeName="Discovery.BusinessObjects.Controllers.WarehouseController" SelectMethod="GetWarehouses">
                            </asp:ObjectDataSource> </TD></TR><TR><TD style="WIDTH: 69px">Is Same Day?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsSameDay" runat="server" OnCheckedChanged="CheckBoxIsSameDay_CheckedChanged" Checked='<%# Bind("IsSameDay") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 69px">Is Next Day?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsNextDay" runat="server" OnCheckedChanged="CheckBoxIsNextDay_CheckedChanged" Checked='<%# Bind("IsNextDay") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 69px">Is Collection?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsCollection" runat="server" OnCheckedChanged="CheckBoxIsCollection_CheckedChanged" Checked='<%# Bind("IsCollection") %>'></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 69px">Is Special?:</TD><TD style="WIDTH: 128px"><asp:CheckBox id="CheckBoxIsSpecial" runat="server" OnCheckedChanged="CheckBoxIsSpecial_CheckedChanged" Checked='<%# Bind("IsSpecial") %>'></asp:CheckBox></TD></TR></TBODY></TABLE><asp:HiddenField id="Id" runat="server" Value="-1"></asp:HiddenField> <asp:HiddenField id="CheckSum" runat="server" Value="0"></asp:HiddenField> <asp:HiddenField id="UpdatedBy" runat="server" Value='<%# Bind("UpdatedBy") %>'></asp:HiddenField> <!-- AJAX EXTENDERS --><ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender5" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsSameDay" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender6" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsNextDay" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender7" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsCollection" Enabled="false"></ajaxToolkit:ToggleButtonExtender> <ajaxToolkit:ToggleButtonExtender id="ToggleButtonExtender8" runat="server" ImageWidth="16" ImageHeight="16" CheckedImageUrl="~/images/check.gif" UncheckedImageUrl="~/images/uncheck.gif" TargetControlID="CheckBoxIsSpecial" Enabled="false"></ajaxToolkit:ToggleButtonExtender> </DIV>
</InsertItemTemplate>
<ItemTemplate>
<asp:ImageButton id="ButtonEdit" runat="server" SkinID="ButtonEdit" CommandName="Edit"></asp:ImageButton><asp:ImageButton id="ButtonDelete" runat="server" SkinID="ButtonDelete" CommandName="Delete" OnClientClick="return confirm('Are you sure you want to delete?');"></asp:ImageButton><BR /><TABLE><TBODY><TR><TD style="WIDTH: 100px">Code:</TD><TD style="WIDTH: 100px"><asp:Label id="LabelCode" runat="server" Text='<%# Eval("Code") %>'></asp:Label></TD></TR><TR><TD style="WIDTH: 100px">Description:</TD><TD style="WIDTH: 100px"><asp:Label id="LabelDescription" runat="server" Text='<%# Eval("Description") %>'></asp:Label></TD></TR><TR><TD style="WIDTH: 100px">
    Warehouse:</TD><TD style="WIDTH: 100px"><asp:Label id="LabelWarehouseCode" runat="server" Text='<%# Eval("Warehouse.CodeAndDescription")  %>'></asp:Label></TD></TR><TR><TD style="WIDTH: 100px">Is Same Day?:</TD><TD style="WIDTH: 100px"><asp:Image id="ImageIsSameDay" runat="server" SkinID="Check" Visible='<%# Convert.ToBoolean(Eval("IsSameDay")) %>'></asp:Image> <asp:Image id="ImageNotSameDay" runat="server" SkinID="UnCheck" Visible='<%# !Convert.ToBoolean(Eval("IsSameDay")) %>'></asp:Image> </TD></TR><TR><TD style="WIDTH: 100px">Is Next Day?:</TD><TD style="WIDTH: 100px"><asp:Image id="ImageIsNextDay" runat="server" SkinID="Check" Visible='<%# Convert.ToBoolean(Eval("IsNextDay")) %>'></asp:Image> <asp:Image id="ImageNotNextDay" runat="server" SkinID="UnCheck" Visible='<%# !Convert.ToBoolean(Eval("IsNextDay")) %>'></asp:Image> </TD></TR><TR><TD style="WIDTH: 100px">Is Collection?:</TD><TD style="WIDTH: 100px"><asp:Image id="ImageIsCollection" runat="server" SkinID="Check" Visible='<%# Convert.ToBoolean(Eval("IsCollection")) %>'></asp:Image> <asp:Image id="ImageNotCollection" runat="server" SkinID="UnCheck" Visible='<%# !Convert.ToBoolean(Eval("IsCollection")) %>'></asp:Image> </TD></TR><TR><TD style="WIDTH: 100px">Is Special?:</TD><TD style="WIDTH: 100px"><asp:Image id="ImageIsSpecial" runat="server" SkinID="Check" Visible='<%# Convert.ToBoolean(Eval("IsSpecial")) %>'></asp:Image> <asp:Image id="ImageNotSpecial" runat="server" SkinID="UnCheck" Visible='<%# !Convert.ToBoolean(Eval("IsSpecial")) %>'></asp:Image> </TD></TR></TBODY></TABLE>&nbsp; <asp:HiddenField id="Id" runat="server" Value='<%# Eval("Id") %>'></asp:HiddenField> 
</ItemTemplate>
</asp:FormView> 
</ContentTemplate>
    </asp:UpdatePanel>
    <asp:ValidationSummary ID="ValidationSummary1" runat="server" ShowMessageBox="True"
        ShowSummary="False" />
    <asp:ObjectDataSource ID="RouteDataSource" runat="server" DataObjectTypeName="Discovery.BusinessObjects.Route"
        DeleteMethod="DeleteRoute" InsertMethod="SaveRoute" SelectMethod="GetRoute" TypeName="Discovery.BusinessObjects.Controllers.RouteController"
        UpdateMethod="SaveRoute">
        <SelectParameters>
            <asp:QueryStringParameter DefaultValue="-1" Name="routeId" QueryStringField="id"
                Type="Int32" />
        </SelectParameters>
    </asp:ObjectDataSource>
</asp:Content>
