'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Collection
    
    'EntityBoundCollection implementation for table 'StandardFee'
    '*DO* add your modifications to this file
    Public Class StandardFeeBoundCollection
        Inherits Base.StandardFeeBoundCollectionBase
    End Class
End Namespace
