'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Collection
    
    'EntityBoundCollection implementation for table 'TaxonomyDecision'
    '*DO* add your modifications to this file
    Public Class TaxonomyDecisionBoundCollection
        Inherits Base.TaxonomyDecisionBoundCollectionBase
    End Class
End Namespace
