IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'Discovery_SaveTDCShipment')
	BEGIN
		DROP  Procedure  Discovery_SaveTDCShipment
	END

GO

CREATE Procedure Discovery_SaveTDCShipment

	(
		@Id int = null,
		@Type int,
		@OpCoCode varchar(3),
		@OpCoSequenceNumber int,
		@OpCoContactEmail varchar(50),
		@OpCoContactName varchar(50),
		@DespatchNumber varchar(50),
		@RequiredShipmentDate datetime,
		@TransactionTypeCode varchar(10),
		@CustomerReference varchar(50),
		@Instructions varchar(250),
		@RouteCode varchar(10),
		@CustomerNumber varchar(50),
		@CustomerName varchar(50),
		@CustomerAddress1 varchar(50),
		@CustomerAddress2 varchar(50),
		@CustomerAddress3 varchar(50),
		@CustomerAddress4 varchar(50),
		@CustomerAddress5 varchar(50),
		@CustomerPostCode varchar(15),
		@ShipmentNumber varchar(50),
		@ShipmentName varchar(50),
		@ShipmentAddress1 varchar(50),
		@ShipmentAddress2 varchar(50),
		@ShipmentAddress3 varchar(50),
		@ShipmentAddress4 varchar(50),
		@ShipmentAddress5 varchar(50),
		@ShipmentPostCode varchar(15),
		@ShipmentContactName varchar(50), 
		@ShipmentContactTel varchar(50),
		@ShipmentContactEmail varchar(50),
		@SalesBranchCode varchar(50),
		@AfterTime varchar(8),
		@BeforeTime varchar(8),
		@TailLiftRequired bit,
		@VehicleMaxWeight numeric(7, 2),
		@CheckInTime int,
		@DeliveryWarehouseCode varchar(10),
		@StockWarehouseCode varchar(10),
		@DivisionCode varchar(3),
		@GeneratedDateTime datetime,
		@Status int,
		@AuditId int = null,
		@ActualDeliveryDate datetime = null,
		@EstimatedDeliveryDate datetime = null,
		@IsRecurring bit = 0,
		@IsValidAddress bit,
		@LocationCode varchar(50),
		@PAFAddress1 varchar(50),
		@PAFAddress2 varchar(50) = null,
		@PAFAddress3 varchar(50) = null,
		@PAFAddress4 varchar(50) = null,
		@PAFAddress5 varchar(50) = null,
		@PAFPostCode varchar(15),
		@PAFDPS varchar(50),
		@PAFEasting varchar(50) = null,
		@PAFNorthing varchar(50) = null,
		@PAFLocation varchar(50) = null,
		@PAFMatch varchar(50) = null,
		@OpCoShipmentId int = null,
		@SentToWMS datetime = null,
		@SplitSequence int = null,
		@IsSplit bit = 0,
		@TransactionSubTypeCode varchar(50) = null,
		@UpdatedBy varchar(256),
		@CheckSum int
	)

AS

IF @Id =-1
	BEGIN
		INSERT INTO
			Discovery_Shipment
			(
				Type,
				OpCoCode,
				OpCoSequenceNumber,
				OpCoContactEmail,
				OpCoContactName,
				DespatchNumber,
				RequiredShipmentDate,
				TransactionTypeCode,
				CustomerReference,
				Instructions,
				RouteCode,
				CustomerNumber,
				CustomerName,
				CustomerAddress1,
				CustomerAddress2,
				CustomerAddress3,
				CustomerAddress4,
				CustomerAddress5,
				CustomerPostCode,
				ShipmentNumber,
				ShipmentName,
				ShipmentAddress1,
				ShipmentAddress2,
				ShipmentAddress3,
				ShipmentAddress4,
				ShipmentAddress5,
				ShipmentPostCode,
				ShipmentContactName,
				ShipmentContactTel,
				ShipmentContactEmail,
				SalesBranchCode,
				AfterTime,
				BeforeTime,
				TailLiftRequired,
				VehicleMaxWeight,
				CheckInTime,
				DeliveryWarehouseCode,
				StockWarehouseCode,
				DivisionCode,
				GeneratedDateTime,
				Status,
				AuditId,
				ActualDeliveryDate,
				EstimatedDeliveryDate,
				IsRecurring,
				IsValidAddress,
				LocationCode,
				PAFAddress1,
				PAFAddress2,
				PAFAddress3,
				PAFAddress4,
				PAFAddress5,
				PAFPostCode,
				PAFDPS,
				PAFEasting,
				PAFNorthing,
				PAFLocation,
				PAFMatch,
				OpCoShipmentId,
				SentToWMS,
				SplitSequence,
				IsSplit,
				TransactionSubTypeCode,
				UpdatedDate,
				UpdatedBy
			)
		VALUES
			(
				@Type,
				@OpCoCode,
				@OpCoSequenceNumber,
				@OpCoContactEmail,
				@OpCoContactName,
				@DespatchNumber,
				@RequiredShipmentDate,
				@TransactionTypeCode,
				@CustomerReference,
				@Instructions,
				@RouteCode,
				@CustomerNumber,
				@CustomerName,
				@CustomerAddress1,
				@CustomerAddress2,
				@CustomerAddress3,
				@CustomerAddress4,
				@CustomerAddress5,
				@CustomerPostCode,
				@ShipmentNumber,
				@ShipmentName,
				@ShipmentAddress1,
				@ShipmentAddress2,
				@ShipmentAddress3,
				@ShipmentAddress4,
				@ShipmentAddress5,
				@ShipmentPostCode,
				@ShipmentContactName,
				@ShipmentContactTel,
				@ShipmentContactEmail,
				@SalesBranchCode,
				@AfterTime,
				@BeforeTime,
				@TailLiftRequired,
				@VehicleMaxWeight,
				@CheckInTime,
				@DeliveryWarehouseCode,
				@StockWarehouseCode,
				@DivisionCode,
				@GeneratedDateTime,
				@Status,
				@AuditId,
				@ActualDeliveryDate,
				@EstimatedDeliveryDate,
				@IsRecurring,
				@IsValidAddress,
				@LocationCode,
				@PAFAddress1,
				@PAFAddress2,
				@PAFAddress3,
				@PAFAddress4,
				@PAFAddress5,
				@PAFPostCode,
				@PAFDPS,
				@PAFEasting,
				@PAFNorthing,
				@PAFLocation,
				@PAFMatch,
				@OpCoShipmentId,
				@SentToWMS,
				@SplitSequence,
				@IsSplit,
				@TransactionSubTypeCode,
				getdate(),
				@UpdatedBy
			)
		
		SELECT cast(@@IDENTITY  as int)
	END
ELSE
	BEGIN
		UPDATE
			Discovery_Shipment
		SET
				Type=@Type,
				OpCoCode=@OpCoCode,
				OpCoSequenceNumber=@OpCoSequenceNumber,
				OpCoContactEmail=@OpCoContactEmail,
				OpCoContactName=@OpCoContactName,
				DespatchNumber=@DespatchNumber,
				RequiredShipmentDate=@RequiredShipmentDate,
				TransactionTypeCode=@TransactionTypeCode,
				CustomerReference=@CustomerReference,
				Instructions=@Instructions,
				RouteCode=@RouteCode,
				CustomerNumber=@CustomerNumber,
				CustomerName=@CustomerName,
				CustomerAddress1=@CustomerAddress1,
				CustomerAddress2=@CustomerAddress2,
				CustomerAddress3=@CustomerAddress3,
				CustomerAddress4=@CustomerAddress4,
				CustomerAddress5=@CustomerAddress5,
				CustomerPostCode=@CustomerPostCode,
				ShipmentNumber=@ShipmentNumber,
				ShipmentName=@ShipmentName,
				ShipmentAddress1=@ShipmentAddress1,
				ShipmentAddress2=@ShipmentAddress2,
				ShipmentAddress3=@ShipmentAddress3,
				ShipmentAddress4=@ShipmentAddress4,
				ShipmentAddress5=@ShipmentAddress5,
				ShipmentPostCode=@ShipmentPostCode,
				ShipmentContactName=@ShipmentContactName,
				ShipmentContactTel=@ShipmentContactTel,
				ShipmentContactEmail=@ShipmentContactEmail,
				SalesBranchCode=@SalesBranchCode,
				AfterTime=@AfterTime,
				BeforeTime=@BeforeTime,
				TailLiftRequired=@TailLiftRequired,
				VehicleMaxWeight=@VehicleMaxWeight,
				CheckInTime=@CheckInTime,
				DeliveryWarehouseCode=@DeliveryWarehouseCode,
				StockWarehouseCode=@StockWarehouseCode,
				DivisionCode=@DivisionCode,
				GeneratedDateTime=@GeneratedDateTime,
				Status=@Status,
				AuditId=@AuditId,
				ActualDeliveryDate=@ActualDeliveryDate,
				EstimatedDeliveryDate=@EstimatedDeliveryDate,
				IsRecurring=@IsRecurring,
				IsValidAddress=@IsValidAddress,
				LocationCode=@LocationCode,
				PAFAddress1=@PAFAddress1,
				PAFAddress2=@PAFAddress2,
				PAFAddress3=@PAFAddress3,
				PAFAddress4=@PAFAddress4,
				PAFAddress5=@PAFAddress5,
				PAFPostCode=@PAFPostCode,
				PAFDPS=@PAFDPS,
				PAFEasting=@PAFEasting,
				PAFNorthing=@PAFNorthing,
				PAFLocation=@PAFLocation,
				PAFMatch=@PAFMatch,
				OpCoShipmentId=@OpCoShipmentId,
				SentToWMS=@SentToWMS,
				SplitSequence=@SplitSequence,
				IsSplit=@IsSplit,
				TransactionSubTypeCode=@TransactionSubTypeCode,
				UpdatedDate=getdate(),
				UpdatedBy=@UpdatedBy
		WHERE
			Id=@Id AND
			BINARY_CHECKSUM(*) = @CheckSum

		IF @@ROWCOUNT=1
			SELECT @Id 
		ELSE
			SELECT -1
	END
	
GO
