

BEGIN TRANSACTION

INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('AED', 'UNITED ARAB EMIRATES','D823889\accsbxd', 2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ANG','NETHERLANDS ANTILLES','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ARA','ARGENTINA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ATS','AUSTRIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('AUD','AUSTRALIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BDT','BANGLADESH','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BEF','BELGIUM','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BGL','BULGARIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BHD','BAHRAIN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BMD','BERMUDA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BOP','BOLIVIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BRC','BRAZIL','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BSD','BAHAMAS','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('BWP','BOTSWANA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CAD','CANADA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CHF','SWITZERLAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CLP','CHILE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CNY','CHINA (REPUBLIC OF)','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('COP','COLOMBIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CYP','CYPRUS','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('CZK','CZECH REPUBLIC','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('DEM','GERMANY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('DKK','DENMARK','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('DZD','ALGERIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ECS','ECUADOR','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('EEK','ESTONIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('EGP','EGYPT','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ESP','SPAIN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('EUR','EUROPE MISCELLANEOUS','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('FIM','FINLAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('FRF','FRANCE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('GBP','UNITED KINGDOM','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('GRD','GREECE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('GUY','Guernsey','fsys',2005-04-01,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('HKD','HONG KONG','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('HUF','HUNGARY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('IDR','INDONESIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('IEP','IRELAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ILS','ISRAEL','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('INR','INDIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('IRR','IRAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ISK','ICELAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ITL','ITALY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('JER','Jersey','fsys',2005-04-01,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('JMD','JAMAICA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('JOD','JORDAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('JPY','JAPAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('KES','KENYA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('KRW','SOUTH KOREA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('KWD','KUWAIT','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('KYD','CAYMAN ISLANDS','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('LBP','LEBANON','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('LKR','SRI LANKA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('LRD','LIBERIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('LUF','LUXEMBOURG','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('LVL','LATVIA','D823889\accsbxd',2005-03-03,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MAD','MOROCCO','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MGF','MALAGASY (MADAGASCAR','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MTL','MALTA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MUR','MAURITUS AND DEP','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MWK','MALAWI','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MXN','MEXICO','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MYR','MALAYSIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('MZM','Mozambique','fsys',2005-03-03.327,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('NGN','NIGERIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('NLG','NETHERLANDS','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('NOK','NORWAY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('NZD','NEW ZEALAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PEI','PERU','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PGK','PAPUA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PHP','PHILIPPINES','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PKR','PAKISTAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PLN','POLAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('PTE','PORTUGAL','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('QAR','QATAR','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ROL','ROMANIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SAR','SAUDI ARABIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SEK','SWEDEN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SGD','SINGAPORE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SIT','SLOVENIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SKK','SLOVAK REPUBLIC','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SRG','SURINAM','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('STD','SAO TOME & PRINCIPE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('SUR','USSR','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('THB','THAILAND','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('TRL','TURKEY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('TTD','TRINIDAD AND TOBAGO','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('TWD','TAIWAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('TZS','TANZANIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('UGS','UGANDA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('USD','UNITED STATES','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('UYP','URUGUAY','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('VEB','VENEZUELA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('VUV','VANUATU','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('XAF','CENTRAL AFRICAN REP','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('XCD','EAST CARRIBEAN','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ZAR','SOUTH AFRICA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ZMK','ZAMBIA','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ZRZ','ZAIRE','D823889\accsbxd',2005-02-09,null,0)
INSERT INTO [dbo].[Countries]([countryCode], [country], [lastChangedBy], [lastChangedDate], [ts], [deleted])
VALUES('ZWD','ZIMBABWE','fsys',2005-05-12,null,0)
GO
COMMIT TRANSACTION GO

