BEGIN TRANSACTION
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ADP','ANDORRAN PESETA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('AED','UAE DIRHAM','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('AFA','AFGHANISTANIAN AFGANI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ALL','ALBANIAN LEK','D823889\accsbxd',2005-03-020,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ANG','NETH.ANTILLES GUILDE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('AON','ANGOLAN KWANZA','D823889\accsbxd',2005-03-020, 0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ARA','ARGENTINE AUSTRAL','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ARS','ARGENTINIAN PESO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ATS','AUSTRIAN SCHILLING','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('AUD','AUSTRALIAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('AWG','ARUBAN GUILDER','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BBD','BARBADOS DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BDT','BANGLADESH TAKA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BEF','BELGIAN FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BGN','BULGARIA  NEW LEV','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BHD','BAHRAINI DINAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BIF','BURUNDIAN FRANC','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BMD','BERMUDA DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BND','BRUNEI DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BOB','BOLIVIAN BOLIVIANO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BOP','BOLIVIAN PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BRC','BRAZILIAN CRUZADO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BRL','BRAZILIAN REAL','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BSD','BAHAMAS DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BTN','BHUTAN NGULTRUM','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BWP','BOTSWANA PULA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('BZD','BELIZE DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CAD','CANADIAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CHF','SWISS FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CLP','CHILEAN PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CNY','CHINESE RENMINBI','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('COP','COLOMBIAN PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CRC','COSTA RICAN COLON','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CUP','CUBAN PESO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CVE','CAPE VERDE ESCUDO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CYP','CYPRUS POUND','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('CZK','CZECH KORUNA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('DEM','DEUTSCHEMARK','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('DJF','DJIBOUTI FRANC','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('DKK','DANISH KRONE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('DOP','DOMINICAN PESO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('DZD','ALGERIAN DINAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ECS','ECUADORIAN SUCRE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('EEK','ESTONIA KROON','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('EGP','EGYPTIAN POUND','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ESP','SPANISH PESETA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ETB','ETHIOPIA BIRR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('EUR','EURO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('FIM','FINNISH MARKKA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('FJD','FIJIAN DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('FRF','FRENCH FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GBP','STERLING','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GBX','PENCE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GEL','GEORGIAN LARI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GHC','GHANIAN CEDI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GIP','GIBRALTAR POUND','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GMD','GAMBIAN DALASI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GNF','GUINEAN FRANC','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GRD','GREEK DRACHMA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GTQ','GUATEMALAN QUETZAL','D823889\accsbxd',2005-03-021,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GWP','BENIN FRANC','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('GYD','GUYANESE DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('HKD','HONG KONG DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('HNL','HONDURAN LEMPIR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('HRK','CROATIAN KUNA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('HTG','HAITIAN GOURDE','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('HUF','HUNGARIAN FORINT','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('IDR','INDONESIAN RUPIAH','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('IEP','IRISH POUND','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ILS','ISRAELI SHEKEL','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('INR','INDIAN RUPEE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('IQD','IRAQI DINAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('IRR','IRAN RIAL','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ISK','ICELANDIC KRONA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ITL','ITALIAN LIRA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('JMD','JAMAICAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('JOD','JORDANIAN DINAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('JPY','JAPANESE YEN','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KES','KENYA SHILLING','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KHR','CAMBODIAN RIEL','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KMF','COMOROS FRANC','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KRW','SOUTH KOREAN WON','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KWD','KUWAIT DINAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KYD','CAYMAN ISLAND DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('KZT','KAZAK TENGE','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LAK','LOATIAN KIP','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LBP','LEBANESE POUND','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LKR','SRI LANKA RUPEE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LRD','LIBERIAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LSL','LESOTHO LOTI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LTL','LITHUANIAN LITA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LUF','LUXEMBOURG FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LVL','LATVIAN LATS','D823889\accsbxd',2005-03-03,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('LYD','LIBYAN DINAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MAD','MOROCCAN DIRHAM','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MGF','MALAGASY FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MMK','MYANMESE KYAT','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MNT','MONGOLIAN TUGHR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MOP','MACAU PATACA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MRO','MAURITANIA OUGUIYA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MTL','MALTESE LIRA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MUR','MAURITIAN RUPEE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MVR','MALDIVIAN RUFIYAA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MWK','MALAWI KWACHA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MXN','MEXICAN PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MYR','MALAYSIAN RINGGIT','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('MZM','Mozambique Metical','fsys',2005-03-03,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NAD','NAMIBIAN DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NGN','NIGERIAN NAIRA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NIO','NICARAGUAN CORDOBA ORO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NLG','NETHERLANDS GUILDER','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NOK','NORWEGIAN KRONE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NPR','NEPALESE RUPEE','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('NZD','NEW ZEALAND DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('OMR','OMANI RIAL','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PAB','PANAMANIAN BALBOA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PEI','PERUVIAN INTI','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PEN','PERUVIAN NUEVO SOL','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PGK','PAPUA N.GUINEA KINA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PHP','PHILIPPINES PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PKR','PAKISTAN RUPEE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PLN','POLISH ZLOTY','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PTE','PORTUGUESE ESCUDO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('PYG','PARAGUAY GUARANI','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('QAR','QATARI RIAL','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ROL','ROMANIAN LEU','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('RUB','RUSSIAN RUBLE','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SAR','SAUDI ARABIAN RIYAL','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SBD','SOLOMAN ISLANDS DOLLAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SEK','SWEDISH KRONA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SGD','SINGAPORE DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SIT','SLOVENIAN TOLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SKK','SLOVAK KORUNA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SLL','SIERRA LEONE LEONE','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SRG','SURINAM GUILDER','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('STD','SAO TOME/PRINCIP DLR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SUR','RUSSIAN ROUBLE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SVC','EL SAVADORIAN COLON','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SYP','SYRIAN POUND','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('SZL','SWAZILAND LILAG','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('THB','THAILAND BAHT','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TND','TUNISIAN DINAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TOP','TONGAN PA''ANGA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TRL','TURKISH LIRA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TRY','TURKISH LIRA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TTD','TRINIDAD/TOBAGO DLR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TWD','NEW TAIWAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('TZS','TANZANIA SHILLING','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('UAH','UKRAINIAN HRVYNA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('UGS','UGANDA SHILLING','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('UGX','UGANDA SHILLING','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('USD','U.S. DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('UYP','URUGUAY PESO','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('UYU','URUGUAYAN PESO','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('VEB','VENEZUELAN BOLIVAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('VND','VIETNAMESE DONG','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('VUV','VANUATU VATU','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('WST','SAMOAN TALA','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('XAF','C.F.A FRANC','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('XBA','EURO COMPOSITE UNIT','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('XCD','E.CARRIBEAN DOLLAR','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('XEU','EURO CURRENCY UNIT','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('YER','YEMENI RIAL','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('YUM','YUGOSLAV DINAR','D823889\accsbxd',2005-03-02,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ZAR','SOUTH AFRICAN RAND','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ZMK','ZAMBIAN KWACHA','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ZRZ','ZAIRE ZAIRE','D823889\accsbxd',2005-02-09,0)
INSERT INTO [dbo].[Currencies]([currencyCode], [currency], [lastChangedBy], [lastChangedDate], [deleted])
VALUES('ZWD','ZIMBABWE DOLLAR','D823889\accsbxd',2005-02-09,0)
GO
COMMIT TRANSACTION
GO





