'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Views.Service
    
    'Service implementation for table 'vDisplayDistribution'
    '*DO* add your modifications to this file
    Public Class DisplayDistributionService
        Inherits Base.DisplayDistributionServiceBase

        Public Shared Function ParseParams(ByVal data As String) As String
            'remove SQL stuff
            Return EnterpriseObjects.Common.ParseSQLText(data, True, True)
        End Function

        Public Shared Function GetByDistributionID(ByVal ID As Int32, ByVal IsBRU As Boolean) As Entity.DisplayDistribution
            If IsBRU = True Then
                Return GetByBRUDistributionID(ID)
            Else
                Return GetByCountryDistributionID(ID)
            End If
        End Function

        Public Shared Function GetByCountryDistributionID(ByVal ID As Int32) As Entity.DisplayDistribution
            'create a command...
            Dim command As System.Data.SqlClient.SqlCommand = New System.Data.SqlClient.SqlCommand("dbo.usp_GetDistributionDisplayByCountryDistributionID")
            command.CommandType = System.Data.CommandType.StoredProcedure
            'parameters...
            command.Parameters.Add("@SpeciesCountryDistributionID", System.Data.SqlDbType.Int).Value = ParseParams(ID)
            Dim service As service.DisplayDistributionService
            service = Entity.DisplayDistribution.ServiceObject
            Dim TaxonSet As EntitySet.DisplayDistributionSet = CType(service.GetEntitySet(command, GetType(EntitySet.DisplayDistributionSet)), EntitySet.DisplayDistributionSet)
            command.Dispose()
            Return TaxonSet.Entities(0)
        End Function

        Public Shared Function GetByBRUDistributionID(ByVal ID As Int32) As Entity.DisplayDistribution
            'create a command...
            Dim command As System.Data.SqlClient.SqlCommand = New System.Data.SqlClient.SqlCommand("dbo.usp_GetDistributionDisplayByBRUDistributionID")
            command.CommandType = System.Data.CommandType.StoredProcedure
            'parameters...
            command.Parameters.Add("@SpeciesBRUDistributionID", System.Data.SqlDbType.Int).Value = ParseParams(ID)
            Dim service As service.DisplayDistributionService
            service = Entity.DisplayDistribution.ServiceObject
            Dim TaxonSet As EntitySet.DisplayDistributionSet = CType(service.GetEntitySet(command, GetType(EntitySet.DisplayDistributionSet)), EntitySet.DisplayDistributionSet)
            command.Dispose()
            Return TaxonSet.Entities(0)
        End Function

        Public Shared Function GetByTaxon(ByVal KingdomID As Int32, ByVal TaxonID As Int32, ByVal TaxonTypeID As Int32) As Collection.DisplayDistributionBoundCollection
            'create a command...
            Dim command As System.Data.SqlClient.SqlCommand = New System.Data.SqlClient.SqlCommand("dbo.usp_GetDistributionDisplayByTaxon")
            command.CommandType = System.Data.CommandType.StoredProcedure

            'parameters...
            command.Parameters.Add("@KingdomID", System.Data.SqlDbType.Int).Value = ParseParams(KingdomID)
            command.Parameters.Add("@TaxonID", System.Data.SqlDbType.Int).Value = ParseParams(TaxonID)
            command.Parameters.Add("@TaxonTypeID", System.Data.SqlDbType.Int).Value = ParseParams(TaxonTypeID)

            Dim service As Views.Service.DisplayDistributionService
            service = Views.Entity.DisplayDistribution.ServiceObject
            Dim ResultsSet As Views.EntitySet.DisplayDistributionSet = CType(service.GetEntitySet(command, GetType(Views.EntitySet.DisplayDistributionSet)), Views.EntitySet.DisplayDistributionSet)

            command.Dispose()

            Return ResultsSet.Entities()
        End Function
    End Class
End Namespace
