'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class CITESConsignmentData
    Inherits DataSet
    
    Private tableBOConsignment As BOConsignmentDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("BOConsignment")) Is Nothing) Then
                Me.Tables.Add(New BOConsignmentDataTable(ds.Tables("BOConsignment")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BOConsignment As BOConsignmentDataTable
        Get
            Return Me.tableBOConsignment
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As CITESConsignmentData = CType(MyBase.Clone,CITESConsignmentData)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("BOConsignment")) Is Nothing) Then
            Me.Tables.Add(New BOConsignmentDataTable(ds.Tables("BOConsignment")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableBOConsignment = CType(Me.Tables("BOConsignment"),BOConsignmentDataTable)
        If (Not (Me.tableBOConsignment) Is Nothing) Then
            Me.tableBOConsignment.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "CITESConsignmentData"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/CITESConsignmentData.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableBOConsignment = New BOConsignmentDataTable
        Me.Tables.Add(Me.tableBOConsignment)
    End Sub
    
    Private Function ShouldSerializeBOConsignment() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub BOConsignmentRowChangeEventHandler(ByVal sender As Object, ByVal e As BOConsignmentRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOConsignmentDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnPermitReference As DataColumn
        
        Private columnBarCode As DataColumn
        
        Private columnExhibitionX As DataColumn
        
        Private columnExpiryDate As DataColumn
        
        Private columnExportX As DataColumn
        
        Private columnImportX As DataColumn
        
        Private columnImportCountry As DataColumn
        
        Private columnPetX As DataColumn
        
        Private columnReExportX As DataColumn
        
        Private columnReExportCountry As DataColumn
        
        Private columnExportationX As DataColumn
        
        Private columnImportationX As DataColumn
        
        Private columnIssueDate As DataColumn
        
        Private columnIssueLetter As DataColumn
        
        Private columnIssuePlace As DataColumn
        
        Private columnReExportationX As DataColumn
        
        Private columnSpecialConditions As DataColumn
        
        Private columnSurrenderBorderX As DataColumn
        
        Private columnSurrenderIssuingX As DataColumn
        
        Private columnUserName As DataColumn
        
        Private columnSheetDescription As DataColumn
        
        Private columnSheetNumber As DataColumn
        
        Private columnPrintStatus As DataColumn
        
        Private columnPageMofN As DataColumn
        
        Private columnIssuingManagementAuthority_NameAddress As DataColumn
        
        Private columnLocation_Address As DataColumn
        
        Private columnAgent_AuthorisedPartyId As DataColumn
        
        Private columnAgent_PartyName As DataColumn
        
        Private columnExporter_AuthorisedPartyId As DataColumn
        
        Private columnExporter_PartyAddress As DataColumn
        
        Private columnExporter_PartyName As DataColumn
        
        Private columnImporter_AuthorisedPartyId As DataColumn
        
        Private columnImporter_PartyAddress As DataColumn
        
        Private columnImporter_PartyName As DataColumn
        
        Private columnForeignManagementAuthority_NameAddress As DataColumn
        
        Friend Sub New()
            MyBase.New("BOConsignment")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property PermitReferenceColumn As DataColumn
            Get
                Return Me.columnPermitReference
            End Get
        End Property
        
        Friend ReadOnly Property BarCodeColumn As DataColumn
            Get
                Return Me.columnBarCode
            End Get
        End Property
        
        Friend ReadOnly Property ExhibitionXColumn As DataColumn
            Get
                Return Me.columnExhibitionX
            End Get
        End Property
        
        Friend ReadOnly Property ExpiryDateColumn As DataColumn
            Get
                Return Me.columnExpiryDate
            End Get
        End Property
        
        Friend ReadOnly Property ExportXColumn As DataColumn
            Get
                Return Me.columnExportX
            End Get
        End Property
        
        Friend ReadOnly Property ImportXColumn As DataColumn
            Get
                Return Me.columnImportX
            End Get
        End Property
        
        Friend ReadOnly Property ImportCountryColumn As DataColumn
            Get
                Return Me.columnImportCountry
            End Get
        End Property
        
        Friend ReadOnly Property PetXColumn As DataColumn
            Get
                Return Me.columnPetX
            End Get
        End Property
        
        Friend ReadOnly Property ReExportXColumn As DataColumn
            Get
                Return Me.columnReExportX
            End Get
        End Property
        
        Friend ReadOnly Property ReExportCountryColumn As DataColumn
            Get
                Return Me.columnReExportCountry
            End Get
        End Property
        
        Friend ReadOnly Property ExportationXColumn As DataColumn
            Get
                Return Me.columnExportationX
            End Get
        End Property
        
        Friend ReadOnly Property ImportationXColumn As DataColumn
            Get
                Return Me.columnImportationX
            End Get
        End Property
        
        Friend ReadOnly Property IssueDateColumn As DataColumn
            Get
                Return Me.columnIssueDate
            End Get
        End Property
        
        Friend ReadOnly Property IssueLetterColumn As DataColumn
            Get
                Return Me.columnIssueLetter
            End Get
        End Property
        
        Friend ReadOnly Property IssuePlaceColumn As DataColumn
            Get
                Return Me.columnIssuePlace
            End Get
        End Property
        
        Friend ReadOnly Property ReExportationXColumn As DataColumn
            Get
                Return Me.columnReExportationX
            End Get
        End Property
        
        Friend ReadOnly Property SpecialConditionsColumn As DataColumn
            Get
                Return Me.columnSpecialConditions
            End Get
        End Property
        
        Friend ReadOnly Property SurrenderBorderXColumn As DataColumn
            Get
                Return Me.columnSurrenderBorderX
            End Get
        End Property
        
        Friend ReadOnly Property SurrenderIssuingXColumn As DataColumn
            Get
                Return Me.columnSurrenderIssuingX
            End Get
        End Property
        
        Friend ReadOnly Property UserNameColumn As DataColumn
            Get
                Return Me.columnUserName
            End Get
        End Property
        
        Friend ReadOnly Property SheetDescriptionColumn As DataColumn
            Get
                Return Me.columnSheetDescription
            End Get
        End Property
        
        Friend ReadOnly Property SheetNumberColumn As DataColumn
            Get
                Return Me.columnSheetNumber
            End Get
        End Property
        
        Friend ReadOnly Property PrintStatusColumn As DataColumn
            Get
                Return Me.columnPrintStatus
            End Get
        End Property
        
        Friend ReadOnly Property PageMofNColumn As DataColumn
            Get
                Return Me.columnPageMofN
            End Get
        End Property
        
        Friend ReadOnly Property IssuingManagementAuthority_NameAddressColumn As DataColumn
            Get
                Return Me.columnIssuingManagementAuthority_NameAddress
            End Get
        End Property
        
        Friend ReadOnly Property Location_AddressColumn As DataColumn
            Get
                Return Me.columnLocation_Address
            End Get
        End Property
        
        Friend ReadOnly Property Agent_AuthorisedPartyIdColumn As DataColumn
            Get
                Return Me.columnAgent_AuthorisedPartyId
            End Get
        End Property
        
        Friend ReadOnly Property Agent_PartyNameColumn As DataColumn
            Get
                Return Me.columnAgent_PartyName
            End Get
        End Property
        
        Friend ReadOnly Property Exporter_AuthorisedPartyIdColumn As DataColumn
            Get
                Return Me.columnExporter_AuthorisedPartyId
            End Get
        End Property
        
        Friend ReadOnly Property Exporter_PartyAddressColumn As DataColumn
            Get
                Return Me.columnExporter_PartyAddress
            End Get
        End Property
        
        Friend ReadOnly Property Exporter_PartyNameColumn As DataColumn
            Get
                Return Me.columnExporter_PartyName
            End Get
        End Property
        
        Friend ReadOnly Property Importer_AuthorisedPartyIdColumn As DataColumn
            Get
                Return Me.columnImporter_AuthorisedPartyId
            End Get
        End Property
        
        Friend ReadOnly Property Importer_PartyAddressColumn As DataColumn
            Get
                Return Me.columnImporter_PartyAddress
            End Get
        End Property
        
        Friend ReadOnly Property Importer_PartyNameColumn As DataColumn
            Get
                Return Me.columnImporter_PartyName
            End Get
        End Property
        
        Friend ReadOnly Property ForeignManagementAuthority_NameAddressColumn As DataColumn
            Get
                Return Me.columnForeignManagementAuthority_NameAddress
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As BOConsignmentRow
            Get
                Return CType(Me.Rows(index),BOConsignmentRow)
            End Get
        End Property
        
        Public Event BOConsignmentRowChanged As BOConsignmentRowChangeEventHandler
        
        Public Event BOConsignmentRowChanging As BOConsignmentRowChangeEventHandler
        
        Public Event BOConsignmentRowDeleted As BOConsignmentRowChangeEventHandler
        
        Public Event BOConsignmentRowDeleting As BOConsignmentRowChangeEventHandler
        
        Public Overloads Sub AddBOConsignmentRow(ByVal row As BOConsignmentRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddBOConsignmentRow( _
                    ByVal PermitReference As String,  _
                    ByVal BarCode As String,  _
                    ByVal ExhibitionX As String,  _
                    ByVal ExpiryDate As String,  _
                    ByVal ExportX As String,  _
                    ByVal ImportX As String,  _
                    ByVal ImportCountry As String,  _
                    ByVal PetX As String,  _
                    ByVal ReExportX As String,  _
                    ByVal ReExportCountry As String,  _
                    ByVal ExportationX As String,  _
                    ByVal ImportationX As String,  _
                    ByVal IssueDate As String,  _
                    ByVal IssueLetter As String,  _
                    ByVal IssuePlace As String,  _
                    ByVal ReExportationX As String,  _
                    ByVal SpecialConditions As String,  _
                    ByVal SurrenderBorderX As String,  _
                    ByVal SurrenderIssuingX As String,  _
                    ByVal UserName As String,  _
                    ByVal SheetDescription As String,  _
                    ByVal SheetNumber As String,  _
                    ByVal PrintStatus As String,  _
                    ByVal PageMofN As String,  _
                    ByVal IssuingManagementAuthority_NameAddress As String,  _
                    ByVal Location_Address As String,  _
                    ByVal Agent_AuthorisedPartyId As String,  _
                    ByVal Agent_PartyName As String,  _
                    ByVal Exporter_AuthorisedPartyId As String,  _
                    ByVal Exporter_PartyAddress As String,  _
                    ByVal Exporter_PartyName As String,  _
                    ByVal Importer_AuthorisedPartyId As String,  _
                    ByVal Importer_PartyAddress As String,  _
                    ByVal Importer_PartyName As String,  _
                    ByVal ForeignManagementAuthority_NameAddress As String) As BOConsignmentRow
            Dim rowBOConsignmentRow As BOConsignmentRow = CType(Me.NewRow,BOConsignmentRow)
            rowBOConsignmentRow.ItemArray = New Object() {PermitReference, BarCode, ExhibitionX, ExpiryDate, ExportX, ImportX, ImportCountry, PetX, ReExportX, ReExportCountry, ExportationX, ImportationX, IssueDate, IssueLetter, IssuePlace, ReExportationX, SpecialConditions, SurrenderBorderX, SurrenderIssuingX, UserName, SheetDescription, SheetNumber, PrintStatus, PageMofN, IssuingManagementAuthority_NameAddress, Location_Address, Agent_AuthorisedPartyId, Agent_PartyName, Exporter_AuthorisedPartyId, Exporter_PartyAddress, Exporter_PartyName, Importer_AuthorisedPartyId, Importer_PartyAddress, Importer_PartyName, ForeignManagementAuthority_NameAddress}
            Me.Rows.Add(rowBOConsignmentRow)
            Return rowBOConsignmentRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As BOConsignmentDataTable = CType(MyBase.Clone,BOConsignmentDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New BOConsignmentDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnPermitReference = Me.Columns("PermitReference")
            Me.columnBarCode = Me.Columns("BarCode")
            Me.columnExhibitionX = Me.Columns("ExhibitionX")
            Me.columnExpiryDate = Me.Columns("ExpiryDate")
            Me.columnExportX = Me.Columns("ExportX")
            Me.columnImportX = Me.Columns("ImportX")
            Me.columnImportCountry = Me.Columns("ImportCountry")
            Me.columnPetX = Me.Columns("PetX")
            Me.columnReExportX = Me.Columns("ReExportX")
            Me.columnReExportCountry = Me.Columns("ReExportCountry")
            Me.columnExportationX = Me.Columns("ExportationX")
            Me.columnImportationX = Me.Columns("ImportationX")
            Me.columnIssueDate = Me.Columns("IssueDate")
            Me.columnIssueLetter = Me.Columns("IssueLetter")
            Me.columnIssuePlace = Me.Columns("IssuePlace")
            Me.columnReExportationX = Me.Columns("ReExportationX")
            Me.columnSpecialConditions = Me.Columns("SpecialConditions")
            Me.columnSurrenderBorderX = Me.Columns("SurrenderBorderX")
            Me.columnSurrenderIssuingX = Me.Columns("SurrenderIssuingX")
            Me.columnUserName = Me.Columns("UserName")
            Me.columnSheetDescription = Me.Columns("SheetDescription")
            Me.columnSheetNumber = Me.Columns("SheetNumber")
            Me.columnPrintStatus = Me.Columns("PrintStatus")
            Me.columnPageMofN = Me.Columns("PageMofN")
            Me.columnIssuingManagementAuthority_NameAddress = Me.Columns("IssuingManagementAuthority_NameAddress")
            Me.columnLocation_Address = Me.Columns("Location_Address")
            Me.columnAgent_AuthorisedPartyId = Me.Columns("Agent_AuthorisedPartyId")
            Me.columnAgent_PartyName = Me.Columns("Agent_PartyName")
            Me.columnExporter_AuthorisedPartyId = Me.Columns("Exporter_AuthorisedPartyId")
            Me.columnExporter_PartyAddress = Me.Columns("Exporter_PartyAddress")
            Me.columnExporter_PartyName = Me.Columns("Exporter_PartyName")
            Me.columnImporter_AuthorisedPartyId = Me.Columns("Importer_AuthorisedPartyId")
            Me.columnImporter_PartyAddress = Me.Columns("Importer_PartyAddress")
            Me.columnImporter_PartyName = Me.Columns("Importer_PartyName")
            Me.columnForeignManagementAuthority_NameAddress = Me.Columns("ForeignManagementAuthority_NameAddress")
        End Sub
        
        Private Sub InitClass()
            Me.columnPermitReference = New DataColumn("PermitReference", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPermitReference)
            Me.columnBarCode = New DataColumn("BarCode", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnBarCode)
            Me.columnExhibitionX = New DataColumn("ExhibitionX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExhibitionX)
            Me.columnExpiryDate = New DataColumn("ExpiryDate", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExpiryDate)
            Me.columnExportX = New DataColumn("ExportX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExportX)
            Me.columnImportX = New DataColumn("ImportX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImportX)
            Me.columnImportCountry = New DataColumn("ImportCountry", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImportCountry)
            Me.columnPetX = New DataColumn("PetX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPetX)
            Me.columnReExportX = New DataColumn("ReExportX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReExportX)
            Me.columnReExportCountry = New DataColumn("ReExportCountry", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReExportCountry)
            Me.columnExportationX = New DataColumn("ExportationX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExportationX)
            Me.columnImportationX = New DataColumn("ImportationX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImportationX)
            Me.columnIssueDate = New DataColumn("IssueDate", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIssueDate)
            Me.columnIssueLetter = New DataColumn("IssueLetter", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIssueLetter)
            Me.columnIssuePlace = New DataColumn("IssuePlace", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIssuePlace)
            Me.columnReExportationX = New DataColumn("ReExportationX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReExportationX)
            Me.columnSpecialConditions = New DataColumn("SpecialConditions", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSpecialConditions)
            Me.columnSurrenderBorderX = New DataColumn("SurrenderBorderX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSurrenderBorderX)
            Me.columnSurrenderIssuingX = New DataColumn("SurrenderIssuingX", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSurrenderIssuingX)
            Me.columnUserName = New DataColumn("UserName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUserName)
            Me.columnSheetDescription = New DataColumn("SheetDescription", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSheetDescription)
            Me.columnSheetNumber = New DataColumn("SheetNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSheetNumber)
            Me.columnPrintStatus = New DataColumn("PrintStatus", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPrintStatus)
            Me.columnPageMofN = New DataColumn("PageMofN", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPageMofN)
            Me.columnIssuingManagementAuthority_NameAddress = New DataColumn("IssuingManagementAuthority_NameAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIssuingManagementAuthority_NameAddress)
            Me.columnLocation_Address = New DataColumn("Location_Address", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLocation_Address)
            Me.columnAgent_AuthorisedPartyId = New DataColumn("Agent_AuthorisedPartyId", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAgent_AuthorisedPartyId)
            Me.columnAgent_PartyName = New DataColumn("Agent_PartyName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAgent_PartyName)
            Me.columnExporter_AuthorisedPartyId = New DataColumn("Exporter_AuthorisedPartyId", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExporter_AuthorisedPartyId)
            Me.columnExporter_PartyAddress = New DataColumn("Exporter_PartyAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExporter_PartyAddress)
            Me.columnExporter_PartyName = New DataColumn("Exporter_PartyName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExporter_PartyName)
            Me.columnImporter_AuthorisedPartyId = New DataColumn("Importer_AuthorisedPartyId", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImporter_AuthorisedPartyId)
            Me.columnImporter_PartyAddress = New DataColumn("Importer_PartyAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImporter_PartyAddress)
            Me.columnImporter_PartyName = New DataColumn("Importer_PartyName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnImporter_PartyName)
            Me.columnForeignManagementAuthority_NameAddress = New DataColumn("ForeignManagementAuthority_NameAddress", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnForeignManagementAuthority_NameAddress)
        End Sub
        
        Public Function NewBOConsignmentRow() As BOConsignmentRow
            Return CType(Me.NewRow,BOConsignmentRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New BOConsignmentRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(BOConsignmentRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BOConsignmentRowChangedEvent) Is Nothing) Then
                RaiseEvent BOConsignmentRowChanged(Me, New BOConsignmentRowChangeEvent(CType(e.Row,BOConsignmentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BOConsignmentRowChangingEvent) Is Nothing) Then
                RaiseEvent BOConsignmentRowChanging(Me, New BOConsignmentRowChangeEvent(CType(e.Row,BOConsignmentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BOConsignmentRowDeletedEvent) Is Nothing) Then
                RaiseEvent BOConsignmentRowDeleted(Me, New BOConsignmentRowChangeEvent(CType(e.Row,BOConsignmentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BOConsignmentRowDeletingEvent) Is Nothing) Then
                RaiseEvent BOConsignmentRowDeleting(Me, New BOConsignmentRowChangeEvent(CType(e.Row,BOConsignmentRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveBOConsignmentRow(ByVal row As BOConsignmentRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOConsignmentRow
        Inherits DataRow
        
        Private tableBOConsignment As BOConsignmentDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableBOConsignment = CType(Me.Table,BOConsignmentDataTable)
        End Sub
        
        Public Property PermitReference As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.PermitReferenceColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.PermitReferenceColumn) = value
            End Set
        End Property
        
        Public Property BarCode As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.BarCodeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.BarCodeColumn) = value
            End Set
        End Property
        
        Public Property ExhibitionX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ExhibitionXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ExhibitionXColumn) = value
            End Set
        End Property
        
        Public Property ExpiryDate As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ExpiryDateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ExpiryDateColumn) = value
            End Set
        End Property
        
        Public Property ExportX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ExportXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ExportXColumn) = value
            End Set
        End Property
        
        Public Property ImportX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ImportXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ImportXColumn) = value
            End Set
        End Property
        
        Public Property ImportCountry As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ImportCountryColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ImportCountryColumn) = value
            End Set
        End Property
        
        Public Property PetX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.PetXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.PetXColumn) = value
            End Set
        End Property
        
        Public Property ReExportX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ReExportXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ReExportXColumn) = value
            End Set
        End Property
        
        Public Property ReExportCountry As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ReExportCountryColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ReExportCountryColumn) = value
            End Set
        End Property
        
        Public Property ExportationX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ExportationXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ExportationXColumn) = value
            End Set
        End Property
        
        Public Property ImportationX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ImportationXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ImportationXColumn) = value
            End Set
        End Property
        
        Public Property IssueDate As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.IssueDateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.IssueDateColumn) = value
            End Set
        End Property
        
        Public Property IssueLetter As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.IssueLetterColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.IssueLetterColumn) = value
            End Set
        End Property
        
        Public Property IssuePlace As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.IssuePlaceColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.IssuePlaceColumn) = value
            End Set
        End Property
        
        Public Property ReExportationX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ReExportationXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ReExportationXColumn) = value
            End Set
        End Property
        
        Public Property SpecialConditions As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.SpecialConditionsColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.SpecialConditionsColumn) = value
            End Set
        End Property
        
        Public Property SurrenderBorderX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.SurrenderBorderXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.SurrenderBorderXColumn) = value
            End Set
        End Property
        
        Public Property SurrenderIssuingX As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.SurrenderIssuingXColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.SurrenderIssuingXColumn) = value
            End Set
        End Property
        
        Public Property UserName As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.UserNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.UserNameColumn) = value
            End Set
        End Property
        
        Public Property SheetDescription As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.SheetDescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.SheetDescriptionColumn) = value
            End Set
        End Property
        
        Public Property SheetNumber As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.SheetNumberColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.SheetNumberColumn) = value
            End Set
        End Property
        
        Public Property PrintStatus As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.PrintStatusColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.PrintStatusColumn) = value
            End Set
        End Property
        
        Public Property PageMofN As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.PageMofNColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.PageMofNColumn) = value
            End Set
        End Property
        
        Public Property IssuingManagementAuthority_NameAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.IssuingManagementAuthority_NameAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.IssuingManagementAuthority_NameAddressColumn) = value
            End Set
        End Property
        
        Public Property Location_Address As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Location_AddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Location_AddressColumn) = value
            End Set
        End Property
        
        Public Property Agent_AuthorisedPartyId As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Agent_AuthorisedPartyIdColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Agent_AuthorisedPartyIdColumn) = value
            End Set
        End Property
        
        Public Property Agent_PartyName As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Agent_PartyNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Agent_PartyNameColumn) = value
            End Set
        End Property
        
        Public Property Exporter_AuthorisedPartyId As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Exporter_AuthorisedPartyIdColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Exporter_AuthorisedPartyIdColumn) = value
            End Set
        End Property
        
        Public Property Exporter_PartyAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Exporter_PartyAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Exporter_PartyAddressColumn) = value
            End Set
        End Property
        
        Public Property Exporter_PartyName As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Exporter_PartyNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Exporter_PartyNameColumn) = value
            End Set
        End Property
        
        Public Property Importer_AuthorisedPartyId As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Importer_AuthorisedPartyIdColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Importer_AuthorisedPartyIdColumn) = value
            End Set
        End Property
        
        Public Property Importer_PartyAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Importer_PartyAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Importer_PartyAddressColumn) = value
            End Set
        End Property
        
        Public Property Importer_PartyName As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.Importer_PartyNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.Importer_PartyNameColumn) = value
            End Set
        End Property
        
        Public Property ForeignManagementAuthority_NameAddress As String
            Get
                Try 
                    Return CType(Me(Me.tableBOConsignment.ForeignManagementAuthority_NameAddressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBOConsignment.ForeignManagementAuthority_NameAddressColumn) = value
            End Set
        End Property
        
        Public Function IsPermitReferenceNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.PermitReferenceColumn)
        End Function
        
        Public Sub SetPermitReferenceNull()
            Me(Me.tableBOConsignment.PermitReferenceColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsBarCodeNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.BarCodeColumn)
        End Function
        
        Public Sub SetBarCodeNull()
            Me(Me.tableBOConsignment.BarCodeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExhibitionXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ExhibitionXColumn)
        End Function
        
        Public Sub SetExhibitionXNull()
            Me(Me.tableBOConsignment.ExhibitionXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExpiryDateNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ExpiryDateColumn)
        End Function
        
        Public Sub SetExpiryDateNull()
            Me(Me.tableBOConsignment.ExpiryDateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExportXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ExportXColumn)
        End Function
        
        Public Sub SetExportXNull()
            Me(Me.tableBOConsignment.ExportXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImportXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ImportXColumn)
        End Function
        
        Public Sub SetImportXNull()
            Me(Me.tableBOConsignment.ImportXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImportCountryNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ImportCountryColumn)
        End Function
        
        Public Sub SetImportCountryNull()
            Me(Me.tableBOConsignment.ImportCountryColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPetXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.PetXColumn)
        End Function
        
        Public Sub SetPetXNull()
            Me(Me.tableBOConsignment.PetXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsReExportXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ReExportXColumn)
        End Function
        
        Public Sub SetReExportXNull()
            Me(Me.tableBOConsignment.ReExportXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsReExportCountryNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ReExportCountryColumn)
        End Function
        
        Public Sub SetReExportCountryNull()
            Me(Me.tableBOConsignment.ReExportCountryColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExportationXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ExportationXColumn)
        End Function
        
        Public Sub SetExportationXNull()
            Me(Me.tableBOConsignment.ExportationXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImportationXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ImportationXColumn)
        End Function
        
        Public Sub SetImportationXNull()
            Me(Me.tableBOConsignment.ImportationXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIssueDateNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.IssueDateColumn)
        End Function
        
        Public Sub SetIssueDateNull()
            Me(Me.tableBOConsignment.IssueDateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIssueLetterNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.IssueLetterColumn)
        End Function
        
        Public Sub SetIssueLetterNull()
            Me(Me.tableBOConsignment.IssueLetterColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIssuePlaceNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.IssuePlaceColumn)
        End Function
        
        Public Sub SetIssuePlaceNull()
            Me(Me.tableBOConsignment.IssuePlaceColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsReExportationXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ReExportationXColumn)
        End Function
        
        Public Sub SetReExportationXNull()
            Me(Me.tableBOConsignment.ReExportationXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSpecialConditionsNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.SpecialConditionsColumn)
        End Function
        
        Public Sub SetSpecialConditionsNull()
            Me(Me.tableBOConsignment.SpecialConditionsColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSurrenderBorderXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.SurrenderBorderXColumn)
        End Function
        
        Public Sub SetSurrenderBorderXNull()
            Me(Me.tableBOConsignment.SurrenderBorderXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSurrenderIssuingXNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.SurrenderIssuingXColumn)
        End Function
        
        Public Sub SetSurrenderIssuingXNull()
            Me(Me.tableBOConsignment.SurrenderIssuingXColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsUserNameNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.UserNameColumn)
        End Function
        
        Public Sub SetUserNameNull()
            Me(Me.tableBOConsignment.UserNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSheetDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.SheetDescriptionColumn)
        End Function
        
        Public Sub SetSheetDescriptionNull()
            Me(Me.tableBOConsignment.SheetDescriptionColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSheetNumberNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.SheetNumberColumn)
        End Function
        
        Public Sub SetSheetNumberNull()
            Me(Me.tableBOConsignment.SheetNumberColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPrintStatusNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.PrintStatusColumn)
        End Function
        
        Public Sub SetPrintStatusNull()
            Me(Me.tableBOConsignment.PrintStatusColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPageMofNNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.PageMofNColumn)
        End Function
        
        Public Sub SetPageMofNNull()
            Me(Me.tableBOConsignment.PageMofNColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIssuingManagementAuthority_NameAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.IssuingManagementAuthority_NameAddressColumn)
        End Function
        
        Public Sub SetIssuingManagementAuthority_NameAddressNull()
            Me(Me.tableBOConsignment.IssuingManagementAuthority_NameAddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLocation_AddressNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Location_AddressColumn)
        End Function
        
        Public Sub SetLocation_AddressNull()
            Me(Me.tableBOConsignment.Location_AddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAgent_AuthorisedPartyIdNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Agent_AuthorisedPartyIdColumn)
        End Function
        
        Public Sub SetAgent_AuthorisedPartyIdNull()
            Me(Me.tableBOConsignment.Agent_AuthorisedPartyIdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAgent_PartyNameNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Agent_PartyNameColumn)
        End Function
        
        Public Sub SetAgent_PartyNameNull()
            Me(Me.tableBOConsignment.Agent_PartyNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExporter_AuthorisedPartyIdNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Exporter_AuthorisedPartyIdColumn)
        End Function
        
        Public Sub SetExporter_AuthorisedPartyIdNull()
            Me(Me.tableBOConsignment.Exporter_AuthorisedPartyIdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExporter_PartyAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Exporter_PartyAddressColumn)
        End Function
        
        Public Sub SetExporter_PartyAddressNull()
            Me(Me.tableBOConsignment.Exporter_PartyAddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExporter_PartyNameNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Exporter_PartyNameColumn)
        End Function
        
        Public Sub SetExporter_PartyNameNull()
            Me(Me.tableBOConsignment.Exporter_PartyNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImporter_AuthorisedPartyIdNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Importer_AuthorisedPartyIdColumn)
        End Function
        
        Public Sub SetImporter_AuthorisedPartyIdNull()
            Me(Me.tableBOConsignment.Importer_AuthorisedPartyIdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImporter_PartyAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Importer_PartyAddressColumn)
        End Function
        
        Public Sub SetImporter_PartyAddressNull()
            Me(Me.tableBOConsignment.Importer_PartyAddressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsImporter_PartyNameNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.Importer_PartyNameColumn)
        End Function
        
        Public Sub SetImporter_PartyNameNull()
            Me(Me.tableBOConsignment.Importer_PartyNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsForeignManagementAuthority_NameAddressNull() As Boolean
            Return Me.IsNull(Me.tableBOConsignment.ForeignManagementAuthority_NameAddressColumn)
        End Function
        
        Public Sub SetForeignManagementAuthority_NameAddressNull()
            Me(Me.tableBOConsignment.ForeignManagementAuthority_NameAddressColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BOConsignmentRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As BOConsignmentRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As BOConsignmentRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As BOConsignmentRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
