'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace Security
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SecuritySoap", [Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security")>  _
    Public Class SecurityWse
        Inherits Microsoft.Web.Services.WebServicesClientProtocol
        
        Public Sub New()
            MyBase.New
            Me.Url = "http://mydevphoenixwebservice:10080/Security.asmx"
        End Sub
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/GetUserBySPNumber", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Function GetUserBySPNumber(ByVal SPNumber As String) As SSOUser
            Dim results() As Object = Me.Invoke("GetUserBySPNumber", New Object() {SPNumber})
            Return CType(results(0),SSOUser)
        End Function
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/GetUserByName", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Function GetUserByName(ByVal Name As String) As SSOUser
            Dim results() As Object = Me.Invoke("GetUserByName", New Object() {Name})
            Return CType(results(0),SSOUser)
        End Function
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/PopulateDBFromSSOData", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Sub PopulateDBFromSSOData()
            Dim results() As Object = Me.Invoke("PopulateDBFromSSOData", New Object(-1) {})
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SecuritySoap", [Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security")>  _
    Public Class Security
        Inherits Microsoft.Web.Services.WebServicesClientProtocol
        
        Public Sub New()
            MyBase.New
            Me.Url = "http://mydevphoenixwebservice:10080/Security.asmx"
        End Sub
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/GetUserBySPNumber", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Function GetUserBySPNumber(ByVal SPNumber As String) As SSOUser
            Dim results() As Object = Me.Invoke("GetUserBySPNumber", New Object() {SPNumber})
            Return CType(results(0),SSOUser)
        End Function
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/GetUserByName", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Function GetUserByName(ByVal Name As String) As SSOUser
            Dim results() As Object = Me.Invoke("GetUserByName", New Object() {Name})
            Return CType(results(0),SSOUser)
        End Function
        
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security/PopulateDBFromSSOData", RequestNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", ResponseNamespace:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overridable Sub PopulateDBFromSSOData()
            Dim results() As Object = Me.Invoke("PopulateDBFromSSOData", New Object(-1) {})
        End Sub
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security"),  _
     System.SerializableAttribute()>  _
    Public Class SSOUser
        Inherits BaseBO
        
        Private mId As Long
        
        Private mSSOId As Long
        
        Private mSPNumber As String
        
        Private mFullName As String
        
        Private mEmail As String
        
        Private mLocation As String
        
        Private mTitle As String
        
        Private mInitials As String
        
        Private mFirstName As String
        
        Private mSurname As String
        
        Private mGrade As String
        
        Private mUnit As String
        
        Private mRoom As String
        
        Private mExt As String
        
        Private mSTD As String
        
        Private mJobTitle As String
        
        Private mPermissions As System.Int32()
        
        Private mRoles As System.Int32()
        
        Public Overridable Property Id As Long
            Get
                Return mId
            End Get
            Set
                mId = value
            End Set
        End Property
        
        Public Overridable Property SSOId As Long
            Get
                Return mSSOId
            End Get
            Set
                mSSOId = value
            End Set
        End Property
        
        Public Overridable Property SPNumber As String
            Get
                Return mSPNumber
            End Get
            Set
                mSPNumber = value
            End Set
        End Property
        
        Public Overridable Property FullName As String
            Get
                Return mFullName
            End Get
            Set
                mFullName = value
            End Set
        End Property
        
        Public Overridable Property Email As String
            Get
                Return mEmail
            End Get
            Set
                mEmail = value
            End Set
        End Property
        
        Public Overridable Property Location As String
            Get
                Return mLocation
            End Get
            Set
                mLocation = value
            End Set
        End Property
        
        Public Overridable Property Title As String
            Get
                Return mTitle
            End Get
            Set
                mTitle = value
            End Set
        End Property
        
        Public Overridable Property Initials As String
            Get
                Return mInitials
            End Get
            Set
                mInitials = value
            End Set
        End Property
        
        Public Overridable Property FirstName As String
            Get
                Return mFirstName
            End Get
            Set
                mFirstName = value
            End Set
        End Property
        
        Public Overridable Property Surname As String
            Get
                Return mSurname
            End Get
            Set
                mSurname = value
            End Set
        End Property
        
        Public Overridable Property Grade As String
            Get
                Return mGrade
            End Get
            Set
                mGrade = value
            End Set
        End Property
        
        Public Overridable Property Unit As String
            Get
                Return mUnit
            End Get
            Set
                mUnit = value
            End Set
        End Property
        
        Public Overridable Property Room As String
            Get
                Return mRoom
            End Get
            Set
                mRoom = value
            End Set
        End Property
        
        Public Overridable Property Ext As String
            Get
                Return mExt
            End Get
            Set
                mExt = value
            End Set
        End Property
        
        Public Overridable Property STD As String
            Get
                Return mSTD
            End Get
            Set
                mSTD = value
            End Set
        End Property
        
        Public Overridable Property JobTitle As String
            Get
                Return mJobTitle
            End Get
            Set
                mJobTitle = value
            End Set
        End Property
        
        Public Overridable Property Permissions As System.Int32()
            Get
                Return mPermissions
            End Get
            Set
                mPermissions = value
            End Set
        End Property
        
        Public Overridable Property Roles As System.Int32()
            Get
                Return mRoles
            End Get
            Set
                mRoles = value
            End Set
        End Property
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SSOUser))>  _
    Public Class BaseBO
        
        Private mCreated As Boolean
        
        Private mCheckSum As Integer
        
        Private mValidationErrors As ValidationManager
        
        Public Overridable Property Created As Boolean
            Get
                Return mCreated
            End Get
            Set
                mCreated = value
            End Set
        End Property
        
        Public Overridable Property CheckSum As Integer
            Get
                Return mCheckSum
            End Get
            Set
                mCheckSum = value
            End Set
        End Property
        
        Public Overridable Property ValidationErrors As ValidationManager
            Get
                Return mValidationErrors
            End Get
            Set
                mValidationErrors = value
            End Set
        End Property
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security"),  _
     System.SerializableAttribute()>  _
    Public Class ValidationManager
        Inherits ErrorManager
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ValidationManager))>  _
    Public Class ErrorManager
        
        Private mTitle As String
        
        Private mErrors As BOError()
        
        Public Overridable Property Title As String
            Get
                Return mTitle
            End Get
            Set
                mTitle = value
            End Set
        End Property
        
        Public Overridable Property Errors As BOError()
            Get
                Return mErrors
            End Get
            Set
                mErrors = value
            End Set
        End Property
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/uk.gov.defra.Phoenix.WebServices/Security"),  _
     System.SerializableAttribute()>  _
    Public Class BOError
        
        Private mID As ErrorCodes
        
        Private mErrorMessage As String
        
        Private mStage As Integer
        
        Private mIsWarning As Boolean
        
        Private mURL As String
        
        Public Overridable Property ID As ErrorCodes
            Get
                Return mID
            End Get
            Set
                mID = value
            End Set
        End Property
        
        Public Overridable Property ErrorMessage As String
            Get
                Return mErrorMessage
            End Get
            Set
                mErrorMessage = value
            End Set
        End Property
        
        Public Overridable Property Stage As Integer
            Get
                Return mStage
            End Get
            Set
                mStage = value
            End Set
        End Property
        
        Public Overridable Property IsWarning As Boolean
            Get
                Return mIsWarning
            End Get
            Set
                mIsWarning = value
            End Set
        End Property
        
        Public Overridable Property URL As String
            Get
                Return mURL
            End Get
            Set
                mURL = value
            End Set
        End Property
    End Class
    
    Public Enum ErrorCodes
        
        AddressCountMismatch
        
        MissingPerson
        
        MissingBusiness
        
        NoMailingAddress
        
        MailingAddressNoLongerExists
        
        NeedOneActiveAddress
        
        AddressValidationError
        
        PersonValidationError
        
        ContactCountMismatch
        
        NoPrimaryContact
        
        ContactNoLongerExists
        
        ContactValidationError
        
        NeedOneActiveContact
        
        NeedOneEmailAddress
    End Enum
End Namespace
