'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Entity
    
    'Entity implementation for table 'Contact'
    '*DO* add your modifications to this file
    <System.Serializable()>  _
    Public Class Contact
        Inherits Base.ContactBase
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
        End Sub
        
        Public Sub New(ByVal contactId As Integer)
            MyBase.New(contactId)
        End Sub
        
        Public Shadows Sub GetObjectData(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.GetObjectData(info, context)
        End Sub

        Shared Function GetForPerson(ByVal personId As Int32) As EntitySet.ContactSet
            Dim service As service.ContactService = ServiceObject
            Return service.GetEntitySet("Exec usp_GetPersonContacts " & personId, GetType(EntitySet.ContactSet))
        End Function
    End Class
End Namespace
