'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Entity
    
    'Entity implementation for table 'Notes'
    '*DO* add your modifications to this file
    <System.Serializable()>  _
    Public Class Note
        Inherits Base.NoteBase
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
        End Sub
        
        Public Sub New(ByVal noteId As Integer)
            MyBase.New(noteId)
        End Sub
        
        Public Shadows Sub GetObjectData(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.GetObjectData(info, context)
        End Sub

        Shared Function GetForTaxon(ByVal TaxonomyId As Int32) As EntitySet.NoteSet
            Dim service As service.NoteService = ServiceObject
            Return service.GetEntitySet("Exec usp_GetTaxonomyNotes " & TaxonomyId, GetType(EntitySet.NoteSet))
        End Function

        Shared Function GetForParty(ByVal partyId As Int32) As EntitySet.NoteSet
            Dim service As service.NoteService = ServiceObject
            Return service.GetEntitySet("Exec usp_GetPartyNotes " & partyId, GetType(EntitySet.NoteSet))
        End Function

        Shared Function GetForApplication(ByVal applicationId As Int32) As EntitySet.NoteSet
            Dim service As service.NoteService = ServiceObject
            Return service.GetEntitySet("Exec usp_GetApplicationNotes " & applicationId, GetType(EntitySet.NoteSet))
        End Function
    End Class
End Namespace
