'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DataObjects.Entity
    
    'Entity implementation for table 'PermitHistory'
    '*DO* add your modifications to this file
    <System.Serializable()>  _
    Public Class PermitHistory
        Inherits Base.PermitHistoryBase
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
        End Sub
        
        Public Sub New(ByVal permitHistoryId As Integer)
            MyBase.New(permitHistoryId)
        End Sub
        
        Public Sub New(ByVal permitHistoryId As Integer, ByVal tran As System.Data.SqlClient.SqlTransaction)
            MyBase.New(permitHistoryId, tran)
        End Sub
        
        Public Shadows Sub GetObjectData(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.GetObjectData(info, context)
        End Sub

#Region " Get For Permit Info "
        Public Function GetForPermitInfoWithOrder() As [DO].DataObjects.EntitySet.PermitHistorySet
            Return GetForPermitInfoWithOrder(tran:=Nothing)
        End Function

        Public Function GetForPermitInfoWithOrder(ByVal tran As SqlClient.SqlTransaction) As [DO].DataObjects.EntitySet.PermitHistorySet
            Return GetForPermitInfoWithOrder(Me.PermitInfoId, tran)
        End Function

        Public Shared Function GetForPermitInfoWithOrder(ByVal permitInfoId As Int32) As [DO].DataObjects.EntitySet.PermitHistorySet
            Return GetForPermitInfoWithOrder(permitInfoId, Nothing)
        End Function

        Public Shared Function GetForPermitInfoWithOrder(ByVal permitInfoId As Int32, ByVal tran As SqlClient.SqlTransaction) As [DO].DataObjects.EntitySet.PermitHistorySet
            Return GetForPermitInfoWithOrder(permitInfoId, Base.PermitHistoryServiceBase.OrderBy.DefaultOrder, tran)
        End Function

        Public Shared Function GetForPermitInfoWithOrder(ByVal permitInfoId As Int32, ByVal orderby As Service.PermitHistoryService.OrderBy, ByVal tran As SqlClient.SqlTransaction) As [DO].DataObjects.EntitySet.PermitHistorySet
            Return Sprocs.eosp_SelectPermitHistory(Nothing, Nothing, permitInfoId, orderby, tran)
        End Function
#End Region
    End Class
End Namespace
